const constants = {
	FETCH_UNITS: "FETCH_UNITS",
	STORE_UNITS: "STORE_UNITS",
	CLEAR_UNITS: "CLEAR_UNITS",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	CANCEL_FETCHING: "CANCEL_FETCHING"
}

export default constants
