

:verbose: false
:dynamic: true
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>
:timeout: 30

:queues:
  - [live_data]
  - [schedule_live_data]


:schedule:
  LiveData:
    enabled: true
    queue: live_data
  ScheduleLiveData:
    enabled: true
    queue: live_data
