const constants = {
	FETCHING: "FETCHING",
	END_FETCHING: "END_FETCHING",
	STORE_UNITS: "STORE_UNITS",
	CLEAR_UNITS: "CLEAR_UNITS",
	STORE_POWERSCORES: "STORE_POWERSCORES",
	CLEAR_POWERSCORES: "CLEAR_POWERSCORES",
	STORE_SCHEDULE: "STORE_SCHEDULE",
	CLEAR_SCHEDULE: "CLEAR_SCHEDULE",
	STORE_SCHEDULE_DATES: "STORE_SCHEDULE_DATES",
	CLEAR_SCHEDULE_DATES: "CLEAR_SCHEDULE_DATES",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	CLEAR_ERRORS: "CLEAR_ERRORS"
}

export default constants
