const constants = {
	FETCHING: "FETCHING",
	END_FETCHING: "END_FETCHING",
	STORE_UNITS: "STORE_UNITS",
	CLEAR_UNITS: "CLEAR_UNITS",
	STORE_STANDINGS: "STORE_STANDINGS",
	CLEAR_STANDINGS: "CLEAR_STANDINGS",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	CLEAR_ERRORS: "CLEAR_ERRORS"
}

export default constants
