const constants = {
	FETCHING: "FETCHING",
	END_FETCHING: "END_FETCHING",
	CANCEL_FETCHING: "CANCEL_FETCHING",
	STORE_UNITS: "STORE_UNITS",
	CLEAR_UNITS: "CLEAR_UNITS",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR"
}

export default constants
